######################################
# RuuviTag-logger Configuration file #
######################################

# SAMPLE INTERVAL
sample_interval: 60 # seconds

# If you  require the maximum sample rate, set sample_interval to 0.
# Then every time a measurement is received, it is passed
# forward to the ouputs you've specified.
#
# If you plan to keep 7 to 30 days worth of graph, and use a mobile
# browser, you should consider a sample_interval of of 900 (15 min)
# or even up to 3600 (1 hour), to improve page loading speed.

event_queue: 15000

# INFLUX_DB
db: True                                        # Enable or disable database
db_name: ruuvitags
db_user: sensor
db_password: password
db_host: 0.0.0.0
db_port: 8086

# SCREEN
column_width: 14  # Column width on screen (14 default)

# list all your tags
tags:
  "CC:CA:7E:52:CC:34": Backyard
  "FB:E1:B7:04:95:EE": Upstairs
  "E8:E0:C6:0B:B8:C5": Downstairs
